In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()         # deck has a lot of null values thats why we have to drop as no mean , median or mode will be useful to fill this nan data points 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [6]:
df.drop(['deck' , 'embark_town' , 'alive' , 'class', 'who' , 'adult_male'] , axis = 1 , inplace = True)

In [7]:
df['age'].fillna(df['age'].mean() , inplace = True)

In [8]:
df.dropna(subset = ['embarked'] , inplace = True)       # drop rows having null value

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [10]:
# Label Encoding 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [12]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked']) 

In [13]:
df = df.astype(int)
df.head()

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [14]:
x = df.drop('survived' , axis = 1)
y = df['survived']

In [15]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

# logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [17]:
y_pred = model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
accuracy_score(y_test , y_pred)

0.8033707865168539

In [20]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [21]:
print(classification_report(y_test, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       109
           1       1.00      1.00      1.00        69

    accuracy                           1.00       178
   macro avg       1.00      1.00      1.00       178
weighted avg       1.00      1.00      1.00       178



# KNN Model 

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [23]:
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.fit_transform(X_test)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled , y_train)

KNeighborsClassifier()

In [26]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [27]:
accuracy_score(y_test, y_pred_knn)

0.7808988764044944

In [28]:
# logistic regresion give 80% score and knn gives 78% 

In [29]:
confusion_matrix(y_test , y_pred_knn)

array([[90, 19],
       [20, 49]])

In [30]:
print(classification_report(y_test , y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       109
           1       0.72      0.71      0.72        69

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178



# Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB

In [32]:
model_NB = GaussianNB()
model_NB.fit(X_train,y_train)

GaussianNB()

In [33]:
y_pred_NB = model_NB.predict(X_test)

In [34]:
accuracy_score(y_test, y_pred_NB)

0.7752808988764045

Naive Bayes also gave 77% score

In [35]:
confusion_matrix(y_test, y_pred_NB)

array([[84, 25],
       [15, 54]])

In [36]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



# Decision Tree

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
model_DT = DecisionTreeClassifier(random_state = 42)

In [39]:
model_DT.fit(x_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [40]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [41]:
accuracy_score(y_test, y_pred_DT)

0.7696629213483146

In [42]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178



In [43]:
confusion_matrix(y_test, y_pred_DT)

array([[88, 21],
       [20, 49]])

# Support Vector Machine (SVM)

In [44]:
from sklearn.svm import SVC

In [45]:
model_svm = SVC(kernel = 'rbf')

In [46]:
model_svm.fit(x_train_scaled , y_train)

SVC()

In [47]:
y_pred_svm = model_svm.predict(x_test_scaled )

In [48]:
accuracy_score(y_test , y_pred_svm)               # best accuracy score 

0.8258426966292135

In [49]:
confusion_matrix(y_test, y_pred_svm)

array([[96, 13],
       [18, 51]])

In [50]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



# Cross Validation

In [51]:
df

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [53]:
X = df.drop('survived' , axis = 1)
y = df['survived']

In [55]:
from sklearn.model_selection import cross_val_score

In [59]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [66]:
scores = cross_val_score(model_svm,
                         
                         X_scaled, y , cv = 5 , scoring = 'accuracy')

In [67]:
print(scores)

[0.76404494 0.81460674 0.79213483 0.78651685 0.83050847]


In [68]:
print(scores.mean())

0.7975623690725577
