In [2]:
import numpy as np

In [10]:
arr = np.array([1,2,4,7])
arr

array([1, 2, 4, 7])

In [12]:
a = [1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [13]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [14]:
a = [3,6.8]
np.array(a)

array([3. , 6.8])

In [15]:
l = [[1,2,3] , [4,5,6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

above two dimensions there are tensors 


In [17]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [19]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation function

In [26]:
np.random.rand(10)

array([0.94280183, 0.75071833, 0.34443925, 0.32282993, 0.037483  ,
       0.67289228, 0.17762517, 0.47915589, 0.2138445 , 0.56761773])

In [29]:
np.random.randn(10)

array([-1.0089929 ,  0.50721397,  1.89067577, -2.15949671, -0.54318159,
       -0.45281198,  0.17721383, -1.02647771,  1.50291053, -0.35055461])

In [31]:
np.random.randint(6)

4

In [34]:
np.random.randint(2,30,10)

array([ 5, 20, 27, 10,  9, 11, 13,  8, 23, 17], dtype=int32)

Array Attributes

In [35]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.shape

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.dtype

dtype('int64')

array methods


In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum()

np.int64(45)

In [43]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [44]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax()

np.int64(8)

Reshaping and Resizing

In [48]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Numpy Indexing and Slicing of vectors

In [4]:
import numpy as np

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[3::2]

array([14, 16, 18, 20])

Numpy Indexing and Slicing of MATRIX

In [9]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0,3]

np.int64(4)

In [13]:
arr[0:2 , 1:3]

array([[2, 3],
       [7, 8]])

In [14]:
arr[: , 2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [15]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

ARRAY OPERATIONS 

In [18]:
import numpy as np

In [19]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [21]:
arr = a1 + a2
arr

array([ 7,  9, 11, 13, 15])

In [22]:
a1-a2

array([-5, -5, -5, -5, -5])

In [23]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [24]:
a1 // a2

array([0, 0, 0, 0, 0])

In [25]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [26]:
l = [10,20,30,40]
arr = np.array(l)

In [27]:
arr + 10

array([20, 30, 40, 50])

In [30]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [33]:
arr2 

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND SHALLOW COPY

In [34]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [36]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
b = a

In [42]:
b[0] = 80
b

array([80,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
a

array([80,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
b = a.copy()

In [45]:
b[0] = 99

In [46]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
a

array([80,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATIONS

In [49]:
A =  np.array([[1,2] , [3,4]])
B = np.array([[5,6] , [7,8]])


array([[5, 6],
       [7, 8]])

In [50]:
A

array([[1, 2],
       [3, 4]])

In [51]:
B

array([[5, 6],
       [7, 8]])

In [52]:
A @ B

array([[19, 22],
       [43, 50]])

In [53]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

STACKING ARRAY

In [55]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [56]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

SPLITTING ARRAY

In [62]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [68]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [70]:
for i in c:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


EXERCISE

In [75]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [80]:
b = np.sum(s , axis = 1)
b == 45
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("It is valid for rows")

It is valid for rows


In [81]:
c = np.sum(s , axis = 0)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [86]:
a = s[0:3,0:3]
a.sum() == 45


np.True_

In [89]:
for i in range(0,9,3):
    for j in range(0,9,3):
        a = s[i: i+3 , j:j+3]
        print(a.sum() == 45)
        

True
True
True
True
True
True
True
True
True


In [106]:
#Column : [Age,Maths marks , Science marks]
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

In [92]:
# Get the shape of the matrix
data.shape

(5, 3)

In [93]:
# find the average age of students.
# d = data[0: , 0:1]
# d.mean()
np.mean(data[:, 0])

np.float64(18.4)

In [94]:
# extract maths marks of all students 
print(data[:,1])

[85 92 76 65 90]


In [95]:
# find the highest science marks
np.max(data[:, 2])

np.int64(95)

In [98]:
# get details of the student who scored more than 90 in math
data[data[: ,1] > 90]

array([[19, 92, 88]])

In [107]:
data[: , 1] + 5

array([90, 97, 81, 70, 95])

In [119]:
# find how many students are younger than 19
np.sum(data[: , 0] < 19, axis=0)

np.int64(3)

In [120]:
# calculate the average marks in each subject (column-wise mean)
np.mean(data[:, 1:] , axis = 0)

array([81.6, 83.2])

In [122]:
# get data of students who scored atleast 80 in both subjects.
data[(data[: , 1] >= 80) & (data[: , 2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [123]:
# replace all science marks < 75 with 0
data[: , 2][data[:, 2] <75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])